version: '3.7'

x-api-volumes: &api-volumes
  - ./:/app:cached
  - ~/.bash_history:/root/.bash_history

x-app-config: &app-config
  MIX_ENV: dev

x-db-config: &db-config
  DATABASE_NAME: postgres
  DATABASE_USER: postgres
  DATABASE_PASSWORD: pgpassword
  DATABASE_HOST: db
  DATABASE_PORT: 5432
  POSTGRES_PASSWORD: pgpassword

services:
  api:
    build:
      context: ./
      args:
        ENV: dev
    environment:
      <<: [*app-config, *db-config]
    depends_on:
      - db
    volumes: *api-volumes
    stdin_open: true
    tty: true
  db:
    image: postgres:15.1
    environment: *db-config
    ports:
      - '5432:5432'
